name: "Setup environment"
description: "setup"

runs:
  using: "composite"
  steps:
    - name: "Setup :: Node"
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.2

    - name: "Setup :: Yarn and Lerna"
      shell: bash
      run: |
        npm install -g lerna yarn
        yarn config set network-timeout 1000000

    - name: "Bootstrap"
      shell: bash
      run: |
        yarn bootstrap

    - name: "Check :: yarn.lock"
      shell: bash
      run: |
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]

    - name: "Check :: dependencies mismatches"
      shell: bash
      run: |
        npx --yes syncpack list-mismatches

    - name: "Check :: format"
      shell: bash
      run: |
        yarn format:check
